spring.application.name=boss

spring.datasource.url=jdbc:postgresql://localhost:5432/ferrari
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false